### PR TITLE
Tests are moved to OpenJDK image respository

### PR DESCRIPTION
**Pull request by goldmann**

### CODE REVIEW

**Comment by goldmann** [comment]
Tests for OpenJDK image are located here now: https://github.com/jboss-container-images/redhat-openjdk-18-openshift-image/tree/openjdk18-dev/tests/features

**Comment by goldmann** [comment]
We need to remove them from here, because these are triggered twice now.

**Comment by jmtd** [comment]
working on rebasing

**Comment by jmtd** [comment]
Merged in 410a2925d6a581de336405539e845f3e51ff6d1e

Thanks!

**Pull request closed without merging**
