### PR TITLE
[rhpam-3056] Business Central remains "Container Creating" if missing known_hosts file in the githooks configuration

### PR DESCRIPTION
**Pull request by desmax74**
https://issues.redhat.com/browse/RHPAM-3056

@spolti @tchughesiv

### CODE REVIEW

**Comment by spolti** [comment]
we should not edit it. it should be done only on our repositories.

**Comment by desmax74** [comment]
@spolti we can't add or edit under /home/jboss/.ssh because is mounted as a secret by k8s and the secret volumes are red-only (we can't change to readonly false), the other options are add under /etc/ssh or change the /etc/ssh/sshconfig to use a specific path for known_hosts, or use a option with path of known_hosts when ssh is used by the client code, do you have ideas other than these ?

**Comment by spolti** [comment]
I didn't say you to do not do this, just do not use this repo to apply this change, use ours instead :)

**Comment by desmax74** [comment]
@spolti sorry for the misunderstanding :) I've used this because here the user is root there isn't and the dir isn't writable by the other user, is it okay change the user there ?

**Comment by spolti** [comment]
any configuration script processed by cekit will use root.

**Comment by spolti** [comment]
we could, for example add this on the kieserver's configuration script and set the right permissions.

**Comment by desmax74** [comment]
replaced with https://github.com/jboss-container-images/jboss-kie-modules/pull/389/

**Pull request closed without merging**
