### PR TITLE
Separated openshift-layer module to two

### PR DESCRIPTION
**Pull request by dbecvarik**
Signed-off-by: David Becvarik <dbecvari@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull request does not include fixes for other issues than the main ticket
- [ ] Attached commits represent unit of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@redhat.com>` - use `git commit -s`

### CODE REVIEW

**Comment by rcernich** [comment]
I think we should have tried to determine why this was happening so we could address the root of the problem instead of the symptom.  Eventually, we'll be merging modules so they are coarser grained and splitting them apart further goes against that goal.  It also requires modifying all the images to add the new module.

I'll see if I can find the root of the problem.

**Comment by rcernich** [comment]
If this was causing image builds to fail, I wonder if there isn't a problem with the generator in concreate.  All the configure_passwd.sh script does is chmod /etc/passwd.  The passwd file is not used or referenced in any other module.

**Comment by rcernich** [comment]
I don't think this change is bad and is probably something we want to add to our base rhel image.  Furthermore, the openshift-layers module is specific to EAP, so I think it's good that they've been separated.

**Comment by dbecvarik** [comment]
the issue was not configure_passwd but configure_layers one failed AMQ and webserver builds. Theese images need to run configura_passwd but cannot run configure layers.

**Comment by rcernich** [comment]
Ahh, so those images had previously only been running the one script and not both.  Makes sense now.  Thanks @dbecvarik.

**Pull request merged**
