### PR TITLE
[CLOUD-3269] - Don't symlink module jars if the source doesn't exist

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-3269
Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by luck3y** [comment]
@jfdenise FYI

**Comment by jmtd** [comment]
This module is described as "legacy", but, it still seems to be widely used. Is there an alternative version in jboss/container/* ? If not, should we a) move/rename this module into that heirarchy and b) add a compatibility module at this name, or c) transition all the images to the new name?

**Comment by luck3y** [comment]
@jmtd I suspect we really should move this to jboss-eap-modules, since its dealing entirely with jboss-modules layers.

I think we should merge this fix and move it later though :)

**Comment by luck3y** [comment]
@jmtd Any objections to me merging this?

**Pull request merged**
