### PR TITLE
[CLOUD-4075] Upgrade Jolokia to 1.7.1

### PR DESCRIPTION
**Pull request by TomasHofman**
https://issues.redhat.com/browse/CLOUD-4075
https://issues.redhat.com/browse/JBEAP-23179

Upgrade Jolokia to 1.7.1 to include fixes for JDK 9+

Signed-off-by: Tomas Hofman <thofman@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
hi @TomasHofman, do you think you can cherry-pick this fix to 0.39.x branch?

**Review by luck3y — APPROVED** [review]

**Comment by luck3y** [comment]
Thanks @TomasHofman -- this should also go into the 0.45.x branch and be tagged 0.45.4 for EAP 7.4.x / XP 4.

**Comment by luck3y** [comment]
If you open the PR, I'll tag it.

**Comment by TomasHofman** [comment]
Hello @luck3y @spolti ,

the 0.45.x cherry pick is https://github.com/jboss-openshift/cct_module/pull/416
and the 0.39.x is https://github.com/jboss-openshift/cct_module/pull/417

Thanks for reviewing!

**Pull request merged**
