### PR TITLE
[CLOUD-2555] update tests to include EAP CD 13+

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-2555
Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull request does not include fixes for other issues than the main ticket
- [ ] Attached commits represent unit of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@redhat.com>` - use `git commit -s`

### CODE REVIEW

**Comment by luck3y** [comment]
@rcernich Can you review this when you have time? Thanks!

**Comment by luck3y** [comment]
@bstansberry @tremes FYI, updated the cct_module testsuite to run on the EAP CD 13 image.

**Comment by luck3y** [comment]
@rcernich Do I need to wait for @dbecvarik to comment or can I merge?

**Comment by luck3y** [comment]
@rcernich FYI rebased after https://github.com/jboss-openshift/cct_module/pull/262

**Comment by rcernich** [comment]
@dbecvarik, is it required that -tech-preview be in the tags?  @luck3y, is this because the actual image name is defined in image.yaml with -tech-preview, as opposed to using cekit --tech-preview (i.e. that's the actual image name, not the "tagged" name)?

**Comment by luck3y** [comment]
@rcernich The EAP CD image is actually named jboss-eap-7-tech-preview/eap-cd-openshift in image.yaml. I don't recall the reason why.

**Comment by dbecvarik** [comment]
@rcernich it probably is now and I agree its not nice. This creates a lot of unneeded work for Cekit test maintenance.  I don't know if running @jboss-eap-7 test for tech preview image is correct and we can tweak our code this way. We don't even support providing custom tags to test. That probably can be changed. I'll create upstream issue for this, so we can analyse it and track it there.

**Comment by goldmann** [comment]
The image descriptor should not contain the `-tech-preview` suffix in the image family name. The decision whether it is a TP image or not is made at build time using the `--build-tech-preview` flag. We look at TP image as GA images from the development POV. At release time there is made a decision whether the image is good enough to release it as GA. If it's not (or there are other reasons) it's released as TP.

In your case you should remove the `-tech-preview` suffixes from the image descriptor and tests and use the `--build-tech-preview` when building the image for release.

This is how it was designed. If there are reasons against it, let's talk in https://github.com/cekit/cekit/issues/257.

**Comment by rcernich** [comment]
@luck3y, looks like the correct solution is to remove -tech-preview from the image name in image.yaml and use --tech-preview flag when building.

**Comment by luck3y** [comment]
OK, thats fine with me, I'll update this later today.

**Comment by luck3y** [comment]
Closing for now, will reopen a modified version.

**Pull request closed without merging**
