### PR TITLE
[RHPAM-2855] - Broken symlink in registry.redhat.io/rhpam-7/rhpam-kie…

### PR DESCRIPTION
**Pull request by spolti**
…server-rhel8 image
See: https://issues.redhat.com/browse/RHPAM-2855, https://issues.redhat.com/browse/CLOUD-3394

Signed-off-by: spolti <fspolti@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted
- [x] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [x] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Review by jmtd — APPROVED** [review]
LGTM

**Comment by spolti** [comment]
@luck3y are you ok with these changes?

**Review by jmtd — APPROVED** [review]
LGTM

**Comment by spolti** [comment]
@jmtd I am going to merge this and apply it to master, I would need a new tag for 0.39.x, do you mind if I create it, or do you prefer you to create it?

**Review by luck3y — APPROVED** [review]
LGTM, thanks @spolti

**Pull request merged**
