### PR TITLE
Add KieServer capabilities configuration

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: Filippe Spolti <fspolti@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull request does not include fixes for other issues than the main ticket
- [ ] Attached commits represent unit of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@redhat.com>` - use `git commit -s`

### CODE REVIEW

**Comment by sutaakar** [comment]
Wouldn't it be better to allow capability configuration through environment variables, allowing all capabilities of Kie server by default? That way customers can simply choose what functionality they want and what should be hidden.

**Comment by psiroky** [comment]
I think it may be beneficial to make sure users can _disable_ some capabilities. However, I am not sure we should make it trivial to enable e.g. jbpm capabilities for RHDM. Users should never be using those.

**Comment by sutaakar** [comment]
Ok, sounds reasonable.

**Comment by psiroky** [comment]
@sutaakar I would vote to merge this so that we can have an initial version of the image. Once we have that we can improve the capabilities enabling/disabling. WDYT?

**Comment by sutaakar** [comment]
Sounds good, can be merged.

**Comment by psiroky** [comment]
@goldmann could you please take a look and merge this?

**Pull request merged**
