### PR TITLE
[CLOUD-3964] Do not set a default metaspace max value

### PR DESCRIPTION
**Pull request by jfdenise**
https://issues.redhat.com/browse/JBEAP-18968

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Review by luck3y — APPROVED** [review]

**Comment by spolti** [comment]
Is there a specific reason to do it since the default value for it if not set is unlimited? That's not a  good idea when running on ocp with memory constraints.

**Comment by jfdenise** [comment]
@spolti , having a default value causes some reported issues for Wildfly: https://issues.redhat.com/browse/WFCORE-4904

**Comment by luck3y** [comment]
@spolti see https://issues.redhat.com/browse/JBEAP-18968 in general.

**Comment by spolti** [comment]
Well, we had a similar issue with RHPAM images, it seems to me that a fine-tuning of the JVM properties can fix the issue. 
just my 2 cents.

**Review by jmtd — APPROVED** [review]
LGTM but I'd like to know which branches this will be cherry-picked over to please

**Comment by jfdenise** [comment]
@jmtd , we need it in master branch. We would nee a new tag (0.45.0 ?). Thank-you.

**Comment by luck3y** [comment]
Thanks @jmtd, as @jfdenise says we primarily want this for a new release, so a new branch (0.45.x) and tag (0.45.1) I think might be appropriate, or whatever you prefer.

For cherry picking, there is a chance it might go to the EAP 7.3 stream, which would be the 0.32.x branch, but other than that we would have no other plans to backport it, unless its needed by something else.

**Pull request merged**
