### PR TITLE
CLOUD-2049 deterministic execution ordering of valves

### PR DESCRIPTION
**Pull request by bdecoste**
Thanks for submitting your Pull Request!

Please make sure your PR meets following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull request does not include fixes for other issues than the main ticket
- [ ] Attached commits represent unit of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@redhat.com>` - use `git commit -s`

### CODE REVIEW

**Comment by maschmid** [comment]
Does the overlay mean we are replacing any jboss-web.xml that might be in the deployment? 

It does seem too hacky to me.

**Comment by rcernich** [comment]
Good question.  I believe it is merged with the existing content, but I'd need to check.  The KB suggests this as the mechanism for addressing the issue globally.  In either case, it seems we need to determine the side effects of this approach.

**Comment by bdecoste** [comment]
The global jboss-web.xml doesn't replace the individual application's jboss-web.xml. It adds the valves to all deployments.

**Comment by maschmid** [comment]
I have tried it with a simple war with WEB-INF/jboss-web.xml containing:
<jboss-web><context-root>/foobar</context-root></jboss-web>

on the new image the context root seems to be ignored, so it does seem the overlay overrides the deployments' jboss-web.xml

**Comment by bstansberry** [comment]
A deployment-overlay replaces the specified file; there is no merging of content. So putting one in for jboss-web.xml means whatever was already in the app is lost.

**Pull request closed without merging**
